# Generated by Django 5.2.15 on 2026-07-03 03:04

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_note'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='custom',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='custom',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='person',
            name='custom',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CustomFieldDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entity', models.CharField(choices=[('deal', 'deal'), ('person', 'person'), ('organization', 'organization')], max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=60)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('currency', 'Currency'), ('date', 'Date'), ('datetime', 'Datetime'), ('single_select', 'Single Select'), ('multi_select', 'Multi Select'), ('checkbox', 'Checkbox'), ('phone', 'Phone'), ('email', 'Email'), ('url', 'Url'), ('user', 'User')], max_length=15)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_important', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.pipeline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('record_id', models.BigIntegerField()),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='crm.customfielddef')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('value_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('login', 'Login'), ('convert', 'Convert'), ('import', 'Import')], max_length=10)),
                ('model_name', models.CharField(blank=True, max_length=40)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['tenant', 'action', 'created_at'], name='crm_auditlo_tenant__a51410_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='customfielddef',
            constraint=models.UniqueConstraint(fields=('tenant', 'entity', 'key'), name='uniq_cf_key_per_entity'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['tenant', 'definition', 'value_text'], name='cfv_text_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['tenant', 'definition', 'value_number'], name='cfv_number_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['tenant', 'definition', 'value_date'], name='cfv_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('tenant', 'definition', 'record_id'), name='uniq_cf_value_per_record'),
        ),
    ]
