# Generated by Django 5.2.15 on 2026-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_automationrule_automationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='field_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='sla_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger',
            field=models.CharField(choices=[('deal.created', 'deal.created'), ('deal.stage_changed', 'deal.stage_changed'), ('deal.won', 'deal.won'), ('deal.lost', 'deal.lost'), ('lead.created', 'lead.created'), ('lead.converted', 'lead.converted'), ('activity.completed', 'activity.completed'), ('deal.stage_idle', 'deal.stage_idle'), ('activity.overdue', 'activity.overdue')], max_length=40),
        ),
    ]
